In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)


tensor([[-2.1190e-14,  4.5863e-41, -5.4579e-34],
        [ 3.0866e-41,  3.7386e-14,  6.6532e-33],
        [ 2.7045e-43,  0.0000e+00, -2.1190e-14],
        [ 4.5863e-41, -2.1190e-14,  4.5863e-41],
        [ 1.9438e-19,  1.2123e+25,  3.9666e-11]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5930, 0.2192, 0.2247],
        [0.1403, 0.8038, 0.6910],
        [0.6267, 0.2678, 0.3681],
        [0.6214, 0.6605, 0.6100],
        [0.5394, 0.5013, 0.0246]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)


tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.0552, -0.3081,  1.7855],
        [ 1.8881,  1.7707, -1.1063],
        [ 0.2583, -0.2643, -0.4822],
        [-1.5496,  0.9723, -1.1034],
        [ 0.2462, -0.4520,  0.2521]])


Note that size is rows x cols

In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.4304,  0.2275,  2.4685],
        [ 2.6634,  2.1384, -0.1888],
        [ 0.7795,  0.4415, -0.0450],
        [-0.6700,  1.5645, -0.6367],
        [ 0.4641, -0.1395,  1.1987]])


In [9]:
# adds x to y
y.add_(x)
print(y)

tensor([[-1.4304,  0.2275,  2.4685],
        [ 2.6634,  2.1384, -0.1888],
        [ 0.7795,  0.4415, -0.0450],
        [-0.6700,  1.5645, -0.6367],
        [ 0.4641, -0.1395,  1.1987]])


Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [10]:
# Standard numpy indexing works
print(x[:, 1])

tensor([-0.3081,  1.7707, -0.2643,  0.9723, -0.4520])


In [11]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
